### ISSUE TITLE
IS-01: Display wrong username on the website's header (index's header)

### ISSUE THREAD

**Issue by TrHgTung** [Agile101hcmue/Agile101_website#6]
Hi, Quý found an issue about display the user-name on the header not properly, can Tung fix it?

**Comment by tungth-it** [comment]
Ok, I've checked that Tung had fixed it. Check it out! (on MSTeams or Jira's roadmap)

**Comment by tungth-it** [comment]
![image](https://user-images.githubusercontent.com/126162299/228752088-6ed0b292-3268-497f-a547-e3cfa733e80d.png)

It's now working properly!!!
